server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: root
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    
      
      
      
      
      
      
      
      
   
  